name: Angular Frontend CI/CD Pipeline

# Run this workflow on pushes and pull requests to these branches
on:
  push:
    branches:
      - develop
      - stage
      - main
  pull_request:
    branches:
      - develop
      - stage
      - main

jobs:
  # Step 1: Build the Angular App
  build:
    name: Build Angular App 16
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repo
      - name: Checkout code from the repo
        uses: actions/checkout@v2

      # Set up Node.js to use it in the workflow
      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run Angular build based on the branch (build for dev, stage, or main)
      - name: Build Angular App
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            npm run build -- --configuration=development
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            npm run build -- --configuration=staging
          else
            npm run build -- --configuration=production
          fi

  # Step 2: Deploy to GitHub Pages
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js (again in this job)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Install dependencies again (because we are in a different job)
      - name: Install Dependencies
        run: npm install

      # Deploy to GitHub Pages only for main branch
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          npm run build -- --configuration=production
          npx angular-cli-ghpages --dir=dist/YOUR-PROJECT-NAME
