name: Angular Frontend CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - stage
      - main
  pull_request:
    branches:
      - develop
      - stage
      - main

jobs:
  # Step 1: Build the Angular App
  build:
    name: Build Angular App 16
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from the repo
        uses: actions/checkout@v2

      - name: Set up Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            npm run build -- --configuration=development
          elif [[ "${{ github.ref }}" == "refs/heads/stage" ]]; then
            npm run build -- --configuration=staging
          else
            npm run build -- --configuration=production
          fi

  # Step 2: Deploy to GitHub Pages
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        run: |
          npx angular-cli-ghpages --dir=dist/task-manager
